common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainpage/', include('mainpage.urls')),
    path('common/', include('common.urls')),
    path('regexpenses/', include('regexpenses.urls')),

]

mainpage/urls.py
from django.urls import path

from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.index, name='index'),

]

regexpenses/urls.py
from django.urls import path

from . import views

app_name = 'regexpenses'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/', views.add_data, name='nodata'),
    path('<int:reg_id>/', views.detail, name='detail'),
    path('iptamt/', views.input_tamt, name='iptamt'),
    path('delete/<int:rid>', views.del_itm, name='delete_itm'),
]

common/models.py
from django.db import models

# Create your models here.

mainpage/models.py
from django.db import models

# Create your models here.

regexpenses/models.py
from django.db import models


class expenses(models.Model):
    CHOICES = (
        (0, '기본식비(외식등)'),
        (1, '유흥(놀고먹는거)'),
        (2, '기타'),
    )

    cat = models.IntegerField(default=0, choices=CHOICES)
    subject = models.CharField(max_length=100)
    description = models.TextField()
    amt = models.CharField(max_length=10)
    amtdate = models.DateTimeField()
    monthly_avr = models.CharField(max_length=10)

class daily_target(models.Model):
    target = models.CharField(max_length=20)

regexpenses/forms.py
from django import forms
from regexpenses.models import expenses


class regExp(forms.ModelForm):
    class Meta:
        model = expenses
        fields = ['cat','subject','description','amt','amtdate']
        labels = {'cat':'분류','subject':'제목', 'description':'상세','amt':' 지출금액','amtdate':'지출일자'}

common/views.py
from django.shortcuts import render

# Create your views here.

mainpage/views.py
from django.shortcuts import render, get_object_or_404, redirect

def index(request):
    user = request.user
    if user.is_authenticated:
        return render(request,'mainpage/index_page.html')
    else:
        return redirect('common:login')

regexpenses/views.py
import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import expenses, daily_target
from .forms import regExp
from django.core.paginator import Paginator
from datetime import date, timedelta
from django.db.models import Count
#from django.contrib import messages
#from django.db.models import Q



def index(request):
    user = request.user
    if user.is_authenticated:
        tamt = daily_target.objects.all()
        if tamt:
            mny = tamt[0].target
        else:
            mny = 0
        page = request.GET.get('page', '1')
        kw = request.GET.get('kw', '')  # 검색어
        kw_type = request.GET.get('type','')
        data = expenses.objects.filter(amtdate__range=[date.today() - timedelta(days=60), date.today()]).values().all()
        if kw:
            if kw_type == 'category':
                if kw == '기본식비(외식등)':
                    ids = 0
                elif kw == '유흥(놀고먹는거)':
                    ids = 1
                elif kw == '기타':
                    ids = 2
                data = expenses.objects.filter(cat = ids)
            elif kw_type == 'subject':
                data = expenses.objects.filter(subject = kw)
            elif kw_type == 'date':
                data = expenses.objects.filter(amtdate = kw)
        paginator = Paginator(data, 15)  # 페이지당 15개씩 보여주기
        page_obj = paginator.get_page(page)
        context = {'exp_list': page_obj, 'page':page, 'kw':kw, 'kw_type':kw_type,'tamt':mny}
        return render(request, 'regexpenses/exp_list.html', context)
    else:
        return redirect('common:login')


def add_data(request):
    tamt = daily_target.objects.all()
    if tamt:
        mny = tamt[0].target
    else:
        mny = 0
    if request.method == 'POST':
        form = regExp(request.POST)
        if form.is_valid():
            tdate = request.POST.get('adate')
            datas = form.save(commit=False)
            datas.save()
            return redirect('regexpenses:index')
    else:
        today = timezone.now().strftime('%Y-%m-%d')
        form = regExp()
        context = {'form': form,'cond':False,'tamt':mny,'adate':today,'rid':'0'}
        return render(request, 'regexpenses/detail.html', context)


def detail(request,reg_id):
    tamt = daily_target.objects.all()
    if tamt:
        tamt = tamt[0].target
    else:
        tamt = 0
    data = get_object_or_404(expenses, pk=reg_id)
    if request.method == 'POST':
        form = regExp(request.POST, instance=data)
        if form.is_valid():
            datas = form.save(commit=False)
            datas.save()
            listup = expenses.objects.filter(id=reg_id)
            context = {'exp_list': listup,'cond':True}
            return render(request, 'regexpenses/exp_list.html', context)
    else:
        form = regExp(instance=data)
        lists = expenses.objects.filter(id=reg_id)
        adate = lists[0].amtdate
        adate = adate.strftime('%Y-%m-%d')
        context = {'adate':adate,'form': form,'cond':True,'tamt':tamt,'rid':reg_id}
        return render(request, 'regexpenses/detail.html', context)

def input_tamt(request):
    tamt = daily_target.objects.all()
    if "GET" == request.method:
        if tamt:
            mny = tamt[0].target
        else:
            mny = 0
        context = {'tamt': mny}
        return render(request, 'regexpenses/input_amt.html',context)
    else:
        user = request.user
        if user.is_authenticated:
            page = request.GET.get('page', '1')
            kw = request.GET.get('kw', '')  # 검색어
            kw_type = request.GET.get('type', '')
            data = expenses.objects.filter(
                amtdate__range=[date.today() - timedelta(days=60), date.today()]).values().all()
            if kw:
                if kw_type == 'category':
                    if kw == '기본식비(외식등)':
                        ids = 0
                    elif kw == '유흥(놀고먹는거)':
                        ids = 1
                    elif kw == '기타':
                        ids = 2
                    data = expenses.objects.filter(cat=ids)
                elif kw_type == 'subject':
                    data = expenses.objects.filter(subject=kw)
                elif kw_type == 'date':
                    data = expenses.objects.filter(amtdate=kw)
            paginator = Paginator(data, 15)  # 페이지당 15개씩 보여주기
            page_obj = paginator.get_page(page)
        mny = request.POST["target_money"]
        del_data = tamt
        del_data.delete()
        datas = daily_target()
        datas.target = mny
        datas.save()
        context = {'exp_list': page_obj, 'page': page, 'kw': kw, 'kw_type': kw_type,'tamt':mny}
        return render(request, 'regexpenses/exp_list.html', context)


def del_itm(request,rid):
    print(11111)
    datas = expenses.objects.get(id=rid)
    datas.delete()
    listup = expenses.objects.all()
    context = {'exp_list': listup, 'cond': True}
    return render(request, 'regexpenses/exp_list.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>For My Life, For My Dream...</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<br><br><br><br><br><br><br>
<h3 style=" font:돋음; text-align:center">For My Life, For My Dream</h3>
<br>
<div style = "width : 400px; background-color :#F5F5F5; border: 0px" class = "container my-3" >
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <br>
        <br>
        <label for="username">사용자ID</label>
        <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        <br>
        <label for="password">비밀번호</label>
        <input type="password" class="form-control" name="password" id="password"
               value="{{ form.password.value|default_if_none:'' }}">
        <br>
        <button type="submit" class="btn btn-primary">로그인</button>
        <br>
    </form>
    <br>
</div>

{% endblock %}

templates/mainpage/index_page.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class = "d-flex justify-content-evenly" >
    <div class="badge bg-primary text-wrap" style="width: 25%; text-align:left;margin-right:10px">
        <p class="fs-3" style="text-align:center"><a href = "{% url 'regexpenses:index' %}" style = "color:white; text-decoration:none">지출</a></p>
        <br>
        <br>
        <p class="fs-5">목표로 하는 하루 평균 사용액을 설정하세요.</p>
        <br>
        <p class="fs-5">하루동안 실제 사용액과 매일매일 평균 사용액의 차이를 월단위로 표시합니다.</p>
    </div>
    <div class="badge bg-success text-wrap" style="width: 25%; text-align:left; margin-right:10px">
        <p class="fs-3" style="text-align:center">메모</p>
        <br>
        <br>
        <p class="fs-5">어떤 형식이든 상관 없습니다.  </p>
        <br>
        <p class="fs-5">자유롭게 손가락 가는데로 마음껏 키보드를 두들기면 됩니다.</p>
    </div>
    <div class="badge bg-secondary text-wrap" style="width: 25%; text-align:left;margin-right:10px">
        <p class="fs-3" style="text-align:center">일정</p>
        <br>
        <br>
        <p class="fs-5">달력에 일정을 입력하세요.  </p>
        <br>
        <p class="fs-5">구글 켈린더와도 연동됩니다.</p>
    </div>
    <div class="badge bg-dark text-wrap" style="width: 25%; text-align:left;margin-right:10px">
        <p class="fs-3" style="text-align:center">할일</p>
        <br>
        <br>
        <p class="fs-5">꼭 해야 하는일 </p>
        <br>
        <p class="fs-5">메모하고, 피드백이 필요한 날짜와 시간을 입력하세요</p>
    </div>

</div>
{% endblock %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'mainpage:index' %}">MyNote</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                     <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/regexpenses/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class = "my-3">
        <div style="float:left; width:33%; background-color:#74B1C2"><h5 class="my-3 border-bottom pb-2">지출내역 등록</h5></div>
        <div style="float:left; width:33%; background-color:#74B1C2"><h5 class="my-3 border-bottom pb-2">목표금액 : {{ tamt }}</h5></div>
        <div style="float:left; width:33%; background-color:#74B1C2"><h5 class="my-3 border-bottom pb-2">이번달 일평균 사용액 : </h5></div>
    </div>
    <div>
    <form method="post" id="edtform">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div style="float: left; width: 40%;">
        <div class="mb-3">
            <label for="cat_select" class="form-label" style = "width:50%">분류</label>
            <select style="width: 80%;height:30px"  class="form_select" id = "cat_select" name = "cat_select" >
                {% for v, k in form.fields.cat.choices %}
                    <option value = "{{ v }}" {% if form.fields.cat.value == v %} selected {% endif %}>{{ k }}</option>
                {% endfor %}
            </select>
            <input type = "hidden" id = "cat" name="cat" value = "{{ type }}">
            <input type = "hidden" id = "rid" name ="rid" value = "{{ rid }}">

            <label for="subject" class="form-label" style = "width:50%">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}" style="width:200px;height:25px;font-size:18px;">

            <label for="description" class="form-label">상세내역</label>
            <input type="text" class="form-control" name="description" id="description" style = "width:80%;font-size:18px;"
                   value="{{ form.description.value|default_if_none:'' }}">

            <label for="amt" class="form-label">지출금액</label>
            <input type="text" class="form-control" name="amt" id="amt"
                   value="{{ form.amt.value|default_if_none:'' }}" style="width:200px;height:25px;font-size:18px;">

            <label for="amtdate" class="form-label">지출일자</label>
            {% if adate %}
            <input type="date" class="form-control" name="amtdate" id="amtdate"
                   value="{{ adate }}" style="width:200px;height:25px;font-size:18px;">
            {% else %}
            <input type="date" class="form-control" name="amtdate" id="amtdate"
                   value="{{ form.amtdate.value|default_if_none:'' }}" style="width:200px;height:25px;font-size:18px;">
            {% endif %}
        </div>
            <button type="submit" class="btn btn btn-outline-secondary" id = 'btn_go'>입력/수정</button>
            <button type="submit" class="btn btn btn-outline-secondary" id = 'btn_del' onclick="fn_del();">삭제</button>
            <a href="{% url 'regexpenses:index' %}">돌아가기</a>
        </div>
         <div style = "float:right;width:50%">
             pass
        </div>


    </form>
    </div>

</div>

<script type='text/javascript'>
const btn_go = document.getElementById("btn_go");
btn_go.addEventListener('click', function() {
    document.getElementById('cat').value = document.getElementById('cat_select').options[document.getElementById("cat_select").selectedIndex].value;
});
function fn_del(){
    var res = confirm('정말삭제하시겠습니까?');
    if(res){
        window.location.href = "{% url 'regexpenses:delete_itm' rid %}"
        alert("삭제되었습니다.");
        }
    }
</script>
{% endblock %}

templates/regexpenses/exp_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'regexpenses:nodata' %}" class="btn btn-primary">등록</a>
            <a href="{% url 'regexpenses:iptamt' %}" class="btn btn-primary">목표금액</a>
            <h7>목표금액 : {{ tamt }}</h7>
            <h7>일평균 : {{ tamt }}</h7>
        </div>
        <div class="col-6">
            <div class="input-group">
                <select style="width: 6em;"  class="form_control" id = "search_type" >
                <option value="category" {% if kw_type == 'category' %} selected {% endif %}> 분류</option>
                <option value="subject" {% if kw_type == 'subject' %} selected {% endif %}>제목</option>
                <option value="date" {% if kw_type == 'date' %} selected {% endif %}>날짜</option>
                </select>
                <input type="text" placeholder="검색어입력해주세요"  id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="table-success">
            <th>지출일자</th>
            <th>분류</th>
            <th>제목</th>
            <th>내역</th>
            <th>금액</th>
        </tr>
        </thead>
        <tbody>
        {% if exp_list %}
        {% for item in exp_list %}
        <tr>
            {% if item.cat == 0 %}
            <td><a href="{% url 'regexpenses:detail' item.id %}">{{ item.amtdate }}</a></td>
            <td>
                기본식비(외식등)
            </td>
            {% elif item.cat == 1 %}
            <td>
                유흥(놀고먹는거)
            </td>
            {% else %}
            <td>
                기타
            </td>
            {% endif %}
            <td>
                {{ item.subject }}
            </td>
            <td>{{ item.description }}</td>
            <td>{{ item.amt }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">냉무.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if exp_list.has_previous %}
        <li class="page-item">
             <a class="page-link" data-page="{{ exp_list.previous_page_number }}"
           href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true"
           href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in exp_list.paginator.page_range %}
        {% if page_number >= exp_list.number|add:-5 and page_number <= exp_list.number|add:5 %}
        {% if page_number == exp_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if bom1_list.has_next %}
        <li class="page-item">
           <a class="page-link" data-page="{{ exp_list.next_page_number }}"
           href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
             <a class="page-link" tabindex="-1" aria-disabled="true"
           href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
</div>
<form id="searchForm" method="get" action="{% url 'regexpenses:index' %}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="type" name ="type" value = "{{ type }}">
</form>

<script type='text/javascript'>
const stype = document.getElementById('search_type');
const len_type = stype.options.length;
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('type').value = document.getElementById('search_type').options[document.getElementById("search_type").selectedIndex].value;
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('searchForm').submit();
    });
});
const search_type = document.getElementById('search_type');
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('type').value = document.getElementById('search_type').options[document.getElementById("search_type").selectedIndex].value;
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});

</script>
{% endblock %}

templates/regexpenses/input_amt.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container my-3" style = "display:flex; justify-content:center;">
    <div class="row my-3">
        <form method="POST" >
            {% csrf_token %}
        <div class="input-group" style="width:350px">
            <input type="text" aria-label="목표액" class="form-control" placeholder="목표금액설정" name = "target_money">
            <input type="submit" class = "btn btn-primary" value = "입력">
        </div>
        </form>
        {% if tamt %}
        <div style="width:350px;"><h7 class="my-3 border-bottom pb-2">목표금액 : {{ tamt.target }}</h7></div>
        {% else %}
        <div style="width:350px;"><h7 class="my-3 border-bottom pb-2">목표금액 : 미지정</h7></div>
        {% endif %}
    </div>

</div>
{% endblock %}